artifact:
  root_dir_name: artifact

face_blur:
  root_dir_name: face_blur
  cascade_id: 1PPO2MCttsmSqyB-vKh5C7SumwFKuhgyj
  cascade_file_name: face_cascade.xml
  input_video_filename: input.mp4
  output_video_filename: out.mp4