artifact:
  root_dir_name: artifact

face_blur:
  root_dir_name: face_blur
  model_dirve_id: 1AlwKlayaCsiUZHVVtmdRGxldtRnzJ60h
  model_file_name: model.pt
  input_video_filename: input.mp4
  output_video_filename: out.mp4
